# environment.yml
name: splicecov
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - lightgbm
  - ucsc-bigwigtobedgraph
  - numpy>=1.23
  - pandas>=1.5
  - scipy>=1.9
  - scikit-learn>=1.2
  - tqdm>=4.65
  - joblib>=1.3
  - pybigwig>=0.3.22        # skipped on Windows by your script anyway
  - pybedtools>=0.9.0
  - biopython>=1.81
  - pip
  - pip:
      # keep pip section empty (or add extras that aren't on conda)
      - python-dateutil>=2.8.2
      - tzdata>=2022.1
